# spring
spring:
  # redis
  redis:
    password: $E#Hwe1IKZn*NCBv
    host: localhost
    port: 6379
    database: 4
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    timeout: 2000ms
  # Cache
  cache:
    redis:
      time-to-live: 2h
      use-key-prefix: true
  # DataSource
  datasource:
    url: jdbc:mysql://localhost/demo?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: demo
    password: demo
    driver-class-name: com.mysql.cj.jdbc.Driver
  # jpa
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update